apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: studentapp-db
  labels:
    app: studentapp-db
spec:
  selector:
    matchLabels:
      app: studentapp-db
  serviceName: database-service
  replicas: 1  # safer for single DB
  template:
    metadata:
      labels:
        app: studentapp-db
    spec:
      containers:
        - name: studentapp
          image: mariadb:latest
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "yashpatel017"
            - name: MARIADB_DATABASE
              value: student_db
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    app: stuidentapp-db
spec:
  selector:
    app: studentapp-db
  ports:
    - port: 3306
      targetPort: 3306